---
title: "Interactive Dashboard"
author: "Wei Liu"
output: github_document
---

```{r, message = FALSE}
library(dplyr)
library(stringr)
library(lubridate)
library(tidyverse)
library(sf)
library(leaflet)
library(tidyr)
library(geotidy)
library(tidygeocoder)
library(shiny)
library(flexdashboard)

```

# 1 Data

## 1.1 Load data

```{r, message = FALSE}
gps_df = read.csv("./data/one sample/GPS.csv", header=TRUE) # GPS records
base_df = read.csv("./data/one sample/Baseline.csv", header=TRUE) # Baseline Survey dataset
ema_df = read.csv("./data/one sample/EMA.csv", header=TRUE) # EMA dataset
```

## 1.2 Preprocess data

Define the strings of Coordinate Reference System (CRS)

```{r, message = FALSE}
crs_proj <- "+proj=utm +zone=18 +datum=NAD83" # Projection
crs_latlng <- '+proj=longlat +datum=WGS84' # Latitudes and longitudes (This is for visualizing in leaflet map.)
```

### 1.2.1 GPS

```{r, message = FALSE}
# Parse to POSIX
gps_df$time = ymd_hms(gps_df$time)
# Sort the data frame by time (ascending)
gps_df <- gps_df[order(gps_df$time),]
# Convert data frames to objects with geographic information
gps_point <- st_as_sf(gps_df, coords = c("longitude", "latitude"), crs = crs_latlng)
# Convert GPS points into continued polylines (One line-string for one person)
gps_polyline <- gps_point %>%
  summarise(geometry = st_makeline(geometry), uid = first(uid))
```

### 1.2.2 Baseline

```{r, message = FALSE}
# Retrieve drinking locations and corresponding time periods from the baseline table (Currently, we don't have corresponding time)
base_drink_loc1 <- base_df$pDrinkQ2aLoc1
base_drink_loc2 <- base_df$pDrinkQ2aLoc2
base_drink_loc3 <- base_df$pDrinkQ2aLoc3
base_drink_loc <- data.frame(address = c(base_drink_loc1, base_drink_loc2, base_drink_loc3))

rx_pattern <- "(?<=\\().+(?=\\))"
for (i in 1:nrow(base_drink_loc)) {
  if (is.na(base_drink_loc$address[i]) != TRUE & nchar(base_drink_loc$address[i]) > 0) {
    base_drink_loc$address[i] <- str_extract(base_drink_loc$address[i], rx_pattern)
  }
  else {
    base_drink_loc$address[i] <- NA
  }
}
# Drop NA from the data frame
base_drink_loc <- drop_na(base_drink_loc)
# Obtain coordinates by OSM geocoding
base_drink_loc <- tidygeocoder::geocode(base_drink_loc,
                                           address = address,
                                           method = "osm")
# Convert data frames to objects with geographic information
base_drink_points <- st_as_sf(base_drink_loc, coords = c("long", "lat"), crs = crs_latlng)
```

### 1.2.3 EMA

#### 1.2.3.1 Emotion

```{r}
ema_emo <- ema_df[c("uid", "startTime", "expQ1", "expQ2", "expQ3", "expQ7", "expQ8", "expQ8a")]
for (i in 1:nrow(ema_emo)) {
  # Format the start time of the positive/negative emotion
  ema_emo$start_time[i] <- as.character(ymd_hms(paste0(substr(ema_emo$startTime[i], 1, 11), ema_emo$expQ7[i], ":00")))
  # Format the end time of the positive/negative emotion
  if (ema_emo$expQ8[i] == "No") {
    ema_emo$end_time[i] <- as.character(ymd_hms(paste0(substr(ema_emo$startTime[i], 1, 11), ema_emo$expQ8a[i], ":00")))
  }
  else {
    ema_emo$end_time[i] <- ema_emo$startTime[i]
  }
  # Whether the assessment is self-intitiated? 1 as "Yes"; 0 as "No (random prompt)"
  if (ema_emo$expQ1[i] == "a") {
    ema_emo$self[i] <- 1
  }
  else {
    ema_emo$self[i] <- 0
  }
}
ema_emo <- mutate(ema_emo,
                  emo_unpleasant = expQ2,
                  emo_pleasant = expQ3) %>%
  select(c("uid", "self", "start_time", "end_time", "emo_unpleasant", "emo_pleasant"))
# Parse to POSIX
ema_emo$start_time = ymd_hms(ema_emo$start_time)
ema_emo$end_time = ymd_hms(ema_emo$end_time)
# Join GPS records to EMA data set by matching the time stamps to each of the time periods. 
ema_emo_point <- gps_df %>%
  left_join(ema_emo, by = "uid") %>% 
  mutate(inRange = (time >= start_time-5*60 & time <= end_time+5*60)) %>%
  filter(inRange) %>%
  select(uid, time, self, emo_unpleasant, emo_pleasant, longitude, latitude)
# Convert data frames to objects with geographic information
ema_emo_point <- st_as_sf(ema_emo_point, coords = c("longitude", "latitude"), crs = crs_latlng)
```

#### 1.2.3.2 Urge

```{r}
ema_urge <- ema_df[c("uid", "startTime", "drinkingQ1", "drinkingQ7")]
colnames(ema_urge) <- c("uid", "start_time", "urge_alcohol", "urge_drug")
ema_urge$start_time = ymd_hms(ema_urge$start_time)

# Add the scores of urge to drink/use drug from EMA to the gps_df data frame by using the nearest time
ema_urge <- ema_urge[order(ema_urge$start_time),]

gps_df$time_diff <- NA
gps_df$urge_alcohol <- NA
gps_df$urge_drug <- NA

for (i in 1:nrow(ema_urge)) {
  for (j in 1:nrow(gps_df)) {
    gps_df$time_diff[j] <- abs(as.numeric(ema_urge$start_time[i]) - as.numeric(gps_df$time[j]))
    if (j >= 2) {
      if (gps_df$time_diff[j] > gps_df$time_diff[j-1]) {
        gps_df$urge_alcohol[j-1] <- ema_urge$urge_alcohol[i]
        gps_df$urge_drug[j-1] <- ema_urge$urge_drug[i]
        break
      }
    }
  }
}

ema_urge_gps <- gps_df %>% 
  select(uid, time, longitude, latitude, urge_alcohol, urge_drug) %>%
  drop_na(urge_alcohol)
# Convert data frames to objects with geographic information
ema_urge_gps <- st_as_sf(ema_urge_gps, coords = c("longitude", "latitude"), crs = crs_latlng)
```

# 2 Visualization

```{r}
# Create Markers
# Markers for each of the alcohol outlets
alcohol_marker <- awesomeIcons(
  icon = "beer",
  iconColor = "White",
  markerColor = "brown",
  library = "fa"
)

# Create palettes
pal_unpleasant <- colorBin(palette = "Blues", 0:10)
pal_pleasant <- colorBin(palette = "Greens", 0:10)
pal_alcohol <- colorBin(palette = "Reds", 0:10)
pal_drug <- colorBin(palette = "Purples", 0:10)

# Create the map view
map <- leaflet() %>%
  
  # Base groups
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB.Positron") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Esri.WorldImagery") %>%
  
  # Overlay groups
  # GPS Points
  addCircleMarkers(
    data = gps_point,
    group = "GPS Points",
    radius = 3,
    fillColor = "darkblue",
    fillOpacity = 1,
    stroke = FALSE,
    popup = paste0("Date & Time: ", gps_df$time),
    popupOptions = popupOptions(closeButton=FALSE, closeOnClick=TRUE)
  ) %>%
  # GPS Trajectory of this person
  addPolylines(
    data = gps_polyline,
    group = "GPS Polylines",
    opacity = 0.5,
    color = "darkblue",
    weight = 3) %>%
  # Drinking locations
  addAwesomeMarkers(
    data = base_drink_points,
    group = "Drinking Locations",
    icon = alcohol_marker,
    popup = base_drink_points$address
  ) %>%
  # Negative Emotion
  addCircleMarkers(
    data = ema_emo_point,
    group = "Negative Emotion",
    radius = 4,
    fillOpacity = 1,
    stroke = FALSE,
    color = ~pal_unpleasant(emo_unpleasant),
  ) %>%
  addLegend(
    data = ema_emo_point,
    group = "Negative Emotion",
    "bottomright", 
    pal = pal_unpleasant,
    values = ~emo_unpleasant,
    title = "Being Unpleasant",
    opacity = 1
  ) %>%
  # Positive Emotion
  addCircleMarkers(
    data = ema_emo_point,
    group = "Positive Emotion",
    radius = 4,
    fillOpacity = 1,
    stroke = FALSE,
    color = ~pal_pleasant(emo_pleasant),
  ) %>%
  addLegend(
    data = ema_emo_point,
    group = "Positive Emotion",
    "bottomright", 
    pal = pal_pleasant,
    values = ~emo_pleasant,
    title = "Being Pleasant",
    opacity = 1
  ) %>%
  # Urge to drink
  addCircleMarkers(
    data = ema_urge_gps,
    group = "Urge to Drink",
    radius = 4,
    fillOpacity = 1,
    stroke = FALSE,
    color = ~pal_alcohol(urge_alcohol),
  ) %>%
  addLegend(
    data = ema_urge_gps,
    group = "Urge to Drink",
    "bottomright", 
    pal = pal_alcohol,
    values = ~urge_alcohol,
    title = "Urge to Drink",
    opacity = 1
  ) %>%
  # Urge to use drug
  addCircleMarkers(
    data = ema_urge_gps,
    group = "Urge to Use Drug",
    radius = 4,
    fillOpacity = 1,
    stroke = FALSE,
    color = ~pal_drug(urge_drug),
  ) %>%
  addLegend(
    data = ema_urge_gps,
    group = "Urge to Use Drug",
    "bottomright",
    pal = pal_drug,
    values = ~urge_drug,
    title = "Urge to Use Drug",
    opacity = 1
  ) %>%
  
  # layer control
  addLayersControl(
    baseGroups = c("CartoDB.Positron", "Esri.WorldImagery"),
    overlayGroups = c("GPS Points", "GPS Polylines", "Drinking Locations", "Negative Emotion", "Positive Emotion", "Urge to Drink", "Urge to Use Drug"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  hideGroup(c("GPS Points", "Drinking Locations", "Positive Emotion", "Urge to Drink", "Urge to Use Drug"))
```

