---
title: "README"
author: "Wei Liu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      collapse = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      error = FALSE)
```

    

# Introduction

### Background

Global Positioning System (GPS) based mobility data, in combination with Ecological Momentary Assessments (EMAs), has increasingly been utilized by behavioral science researchers to elucidate individuals’ affect and behaviors in the spatial contexts of daily life.

The larger project investigates alcohol consumption and emotions based on self-reported EMAs and GPS records collected by smartphones along with alcohol outlet information. 

### Gap

There is a lack of a user-friendly tools for visualization that integrates data from individual surveys with GPS traces.

### Our Work

We developed “EmoGeoScope”, an interactive dashboard that helps psychologists observe each participant’s spatiotemporal patterns of emotions and behaviors cast in environmental contexts.

### Significance

This dashboard adds value to clinical psychological studies of emotions and behaviors by offering an opportunity to obtain novel insights and generate research questions from a spatiotemporal perspective.


# Usage

### Data Explorer

Selected datasets will be read in through the file upload portal and can be previewed in the Data Explorer.

### Visualization

#### Temporal View - Line Graph

+ In the EMAs:
  + Positive emotions (in green) are measured based on scores 0 to 10.
  + Negative emotions (in blue) are measured based on scores 0 to -10.
  + Higher absolute values indicate more intense emotional experiences.
<br><br>
+ The moving average of emotion is calculated by averaging the emotion scores reported in temporally proximate EMAs.
  
+ Reported behavior outcomes (in red) are represented by ribbons in the background.

#### Spatial View - Map View

+ The map view enables analysts to view any combination of layers generated by built-in functionalities, including GPS trajectories, emotion events, and environmental contexts.

+ The alcohol kernel density layer is obtained by applying kernel density estimation to a geocoded alcohol license dataset.

+ When users select a different range of time in the line graph, the map will also change correspondingly.
